### ISSUE TITLE
デフォルトのアキ量、説明文と値が一致していない

### ISSUE THREAD

**Issue by xrxoxcxox** [yamatoiizuka/palt-typesetting#234]
美しいWeb組版のためのライブラリ、素晴らしいと思います。

READMEを読んでいて、デフォルトのアキ量が四分アキとありましたが、値としては0.2emなことに気がつきました。
単純に計算するのであれば四分 = 25% = 0.25emかと思ったのでIssueを立ててみました。

視覚上の調整などであればすみません。

**Comment by yamatoiizuka** [comment]
本ライブラリにご興味を持ってくださりありがとうございます！

四分アキについて、デフォルト値が 0.25 em だとやや広めに感じたため、
ご推察の通り視覚上の調整として 0.2 em に設定しております。

README に補足説明を追加した上で、こちらの Issue は閉じさせていただきますね。

よろしくお願いいたします！

**Comment by xrxoxcxox** [comment]
ご説明と、早速のご対応ありがとうございます！

Webにおける日本語の組版はまだまだ発展途上ではあると思うので、こちらのライブラリのことも陰ながら応援させていただきます。
