### ISSUE TITLE
ダイアクリティカルマーク付きのラテン文字が、ラテン文字クラスにならないケースがある

### ISSUE THREAD

**Issue by sharapeco** [yamatoiizuka/palt-typesetting#56]
Webにおける日本語ツメ組の課題を解決するプログラムを作成したことに敬意を表します。

さて、ごく稀なケースですが、ダイアクリティカルマーク付きのラテン文字**のみ**で構成される単語があった場合、ラテン文字クラスにならずに和欧間スペースが挿入されない不具合を見つけたので報告とPRをいたします。

ダイアクリティカルマークがない文字を含む単語の場合は、 `latinRegex = /[A-Za-z...]/` を使って `latinRegex.test(segment)` で判定しているのでラテン文字クラスと判定されています。

このケースに該当するのは、フランス語の前置詞 à とイタリア語の動詞の活用系 è、ピンインの a/o/e にマークのついた文字くらいしか思いつきませんが、他にもあるかもしれません。

### Input

```
前置詞à
```

### Expected

```html
前置詞<space><wbr>à
```

### Actual

```html
前置詞<wbr>à
```

### 解決法

ラテン文字かどうかを判定する `latinRegex` の文字集合を次のように変更する

```ts
export const latinRegex = /[\p{scx=Latin}0-9!"#$%&'()*+,\-./:;<=>?@[\\\]^_`{|}~]+/u
```

**Comment by yamatoiizuka** [comment]
本プロジェクトにご興味を持ってくださりありがとうがとうございます。

また早速のご提案もありがとうございます。ラテン文字の判定は少し甘いかなと思っていたので、とても助かりました。

いただいた内容でマージいたしますね！

**Comment by sharapeco** [comment]
早速対応していただいてありがとうございます！

キリル文字やギリシャ文字についても和文との間隔が欲しいですが、どの文字体系を入れるか議論が必要だと思いますので、新しくissue立てますね。
