### ISSUE TITLE
Add space between cyrillic/greek/other scripts and Japanese characters

### ISSUE THREAD

**Issue by sharapeco** [yamatoiizuka/palt-typesetting#61]
現在はラテン文字と日本語で使われる文字の間にスペースが入るようになっていますが、同様に次の文字体系の場合もスペースが欲しいです。

- キリル文字
- ギリシャ文字
- その他

ラテン文字とくらべて使用頻度は少ないですが、ヴィタリ・ユシュマノフ『はじめてでも美味しく作れる ロシア料理』には日本語の文中に材料や料理名を説明するためロシア語が現れます。他にはクラシック音楽でのロシアの作曲家名や作品名の表記が用途として思いつきます。

多言語化して各言語間の印象を統一しよう！という試みでフォントとして他によく実装されているのがヘブライ文字とアラビア文字ですが、日本語の文脈上で出てくることはまずないので（書字方向の扱いもややこしいので）、ひとまずはキリル文字とギリシャ文字だけでいいかと思いました。

「その他」には上付きや下付きの数字、通貨記号などを想定しています。

例文：

- 温室効果ガス CO₂ の削減
- 主要な放射能汚染源である ¹³⁷Cs の回収
- Glyphs 3の価格は€299です

**Comment by yamatoiizuka** [comment]
こちらありがとうございます！
遅くなりましたがそれぞれ対応いたしました。

- #79
- #80

スペースの挿入は、「日本語と日本語でない言語との間」に挿入するように変更しました。
上付きや下付きの数字、通貨記号に関しては、latinRegex をアップデートする形で対応しました。

**Comment by sharapeco** [comment]
文字クラスをどう設計するかについて投げ掛けだったのですが、いろいろと調査して実装までしてくださってどうもありがとうございます。手が空いたら試してみますね！
