### ISSUE TITLE
Doesn't work in Firefox.

### ISSUE THREAD

**Issue by ixkaito** [yamatoiizuka/palt-typesetting#63]
Thank you for the awesome library, but I want to tell you that it doesn't work in Firefox.

**Comment by yamatoiizuka** [comment]
Thank you for highlighting this issue.

This library depends on `Intl.Segmenter` for splitting text into words, so it does not work in Firefox, which lacks support for this feature. In environments where Intl.Segmenter is not supported, the library is designed to skip processing.

To achieve the same visual appearance in Firefox, server-side processing (like SSG) would be necessary.

But the lack of Firefox support in our library might not be immediately obvious, so I will update the README.md to make this clearer, ensuring users are aware of the current compatibility limitations with Firefox.

**Comment by ixkaito** [comment]
@yamatoiizuka Thanks for the details. It seems that Firefox will support `Intl.Segmenter` in version 125. https://caniuse.com/?search=Intl.Segmenter

The purpose is to inform you of this issue, so you can close the issue.
